/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.compras.recurso.filtros.FiltroFacturaContrato;
import com.trascender.compras.recurso.filtros.FiltroFacturaProveedor;
import com.trascender.compras.recurso.filtros.FiltroFacturaServicio;
import com.trascender.compras.recurso.filtros.FiltroFacturaSubsidio;
import com.trascender.compras.recurso.filtros.FiltroLiquidacionCompra;
import com.trascender.compras.recurso.persistent.suministros.Factura;
import com.trascender.compras.recurso.persistent.suministros.LiquidacionCompra;

@Local
public interface BusinessFacturaLocal
{
	
	public static final String JNDI_NAME = "BusinessFacturaLocal";
   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor addFactura( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFactura ) throws java.lang.Exception;

   /**
    * Business method
    */
   public FiltroFacturaProveedor findListaFacturaProveedor(FiltroFacturaProveedor pFiltro) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor findFacturaProveedorByID( long pID ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor updateFacturaProveedor( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFactura ) throws java.lang.Exception;

   /**
    * Business method
    */
   public void deleteFacturaProveedor( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFactura ) throws java.lang.Exception;
   
   /**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio addFacturaSubsidio(com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio pFacturaSubsidio) 
			throws Exception;
	
	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio updateFacturaSubsidio(com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio pFacturaSubsidio) 
			throws Exception;
	
	/**
	 * Business method
	 */
	public void deleteFacturaSubsidio(com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio pFacturaSubsidio) throws Exception;
	
	/**
	 * Business method
	 */
	 public FiltroFacturaSubsidio findListaFacturaSubsidio(FiltroFacturaSubsidio pFiltro) throws java.lang.Exception;
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaSubsidio getFacturaSubsidioPorId(long pId)throws Exception;
	
	/**
	 * Business method
	 * @param pFacturaContrato
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaContrato addFacturaContrato (com.trascender.compras.recurso.persistent.suministros.FacturaContrato pFacturaContrato)throws Exception;
	
	/**
	 * Business method
	 * @param pFacturaContrato
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaContrato updateFacturaContrato (com.trascender.compras.recurso.persistent.suministros.FacturaContrato pFacturaContrato)
			throws Exception;
	
	/**
	 * Business method
	 * @param pFacturaContrato
	 * @throws Exception
	 */
	public void deleteFacturaContrato (com.trascender.compras.recurso.persistent.suministros.FacturaContrato pFacturaContrato)
		throws Exception;
	
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaContrato getFacturaContratoPorID(Long pId) throws Exception;
	
	/**
	 * Business method
	 * @param pProveedor
	 * @param pDesde
	 * @param pHasta
	 * @param pEstado
	 * @param pContrato
	 * @return
	 * @throws java.lang.Exception
	 */
	public FiltroFacturaContrato findListaFacturaContrato(FiltroFacturaContrato pFiltro) throws java.lang.Exception;
	
	/**
	 * Business method
	 * @param pFacturaServicio
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio addFacturaServicio (com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio)
			throws Exception;
	
	/**
	 * Business method 
	 * @param pFacturaServicio
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio updateFacturaServicio (com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio)
			throws Exception;
	
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio getFacturaServicioPorId(Long pId) throws Exception;
	
	/**
	 * Business method
	 * @param pFacturaServicio
	 * @throws Exception
	 */
	public void deleteFacturaServicio(com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio) throws Exception;
	
	/**
	 * Business method
	 * @param pProveedor
	 * @param pDesde
	 * @param pHasta
	 * @param pEstado
	 * @param pBien
	 * @return
	 * @throws java.lang.Exception
	 */
	public FiltroFacturaServicio findListaFacturaServicio(FiltroFacturaServicio pFiltro)	
			throws java.lang.Exception;
	
	
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws java.lang.Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.LineaFactura getLineaFacturaPorId(long pId) throws java.lang.Exception;
	
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws Exception
	 */
	public com.trascender.compras.recurso.persistent.suministros.Factura getFacturaPorId(long pId) throws Exception;
	
	/**
	 * Business method
	 * @param pProveedor
	 * @param pDesde
	 * @param pHasta
	 * @param pEstado
	 * @return
	 * @throws java.lang.Exception
	 */
	public List<Factura> findListaFactura(com.trascender.compras.recurso.persistent.suministros.Proveedor pProveedor,
			java.util.Date pDesde,java.util.Date pHasta, com.trascender.compras.recurso.persistent.suministros.Factura.Estado pEstado)	
			throws java.lang.Exception;
	
	public void addLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public LiquidacionCompra updateLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public void deleteLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public LiquidacionCompra getLiquidacionCompraPorId(Long pId) throws Exception;
	public FiltroLiquidacionCompra findListaLiquidacionCompra(FiltroLiquidacionCompra pFiltro) throws Exception;
}
