/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.compras.exception.TrascenderComprasException;
import com.trascender.compras.recurso.filtros.FiltroAutorizacionSolicitudSuministro;
import com.trascender.compras.recurso.filtros.FiltroEstadoSolicitudSuministro;
import com.trascender.compras.recurso.filtros.FiltroSolicitudSuministro;
import com.trascender.compras.recurso.persistent.suministros.AutorizacionSolicitudSuministro;
import com.trascender.compras.recurso.persistent.suministros.Bien;
import com.trascender.compras.recurso.persistent.suministros.EstadoSolicitudSuministro;
import com.trascender.compras.recurso.persistent.suministros.FirmaPermisoSolicitud;
import com.trascender.compras.recurso.persistent.suministros.LineaOrdenCompra;
import com.trascender.compras.recurso.persistent.suministros.LineaSolicitudSuministro;
import com.trascender.compras.recurso.persistent.suministros.Proveedor;
import com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro;
import com.trascender.compras.recurso.persistent.suministros.UsuarioAutorizadorSolicitudSuministro;
import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.Area;
import com.trascender.framework.recurso.persistent.Usuario;
import com.trascender.framework.recurso.persistent.referencia.CuentaRfr;

@Local
public interface BusinessSolicitudSuministroLocal
{

	public static final String JNDI_NAME = "BusinessSolicitudSuministroLocal";
	public com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro addSolicitudSuministro( com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro pSolicitudSuministro ) throws java.lang.Exception;

	public FiltroSolicitudSuministro findListadoSolicitudSuministro(FiltroSolicitudSuministro pFiltro ) throws java.lang.Exception;

	public FiltroSolicitudSuministro findListadoSolicitudSuministroPorUsuario(FiltroSolicitudSuministro pFiltro) throws java.lang.Exception;

	public com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro updateSolicitudSuministro( com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro pSolicitudSuministro ) throws java.lang.Exception;

	public com.trascender.compras.recurso.persistent.suministros.SolicitudSuministro findSolicitudSuministroByID( long pIdSolicitudSuministro );

	public FiltroAutorizacionSolicitudSuministro findListaAutorizacionSolicitudSuministro(FiltroAutorizacionSolicitudSuministro filtro) throws Exception;

	public void deleteAutorizacionSolicitudSuministro (AutorizacionSolicitudSuministro pAutorizacion) throws Exception;

	public AutorizacionSolicitudSuministro getAutorizacionSolicitudSuministroByID (Long pId) throws Exception;

	public EstadoSolicitudSuministro getEstadoSolicitudSuministroByID(Long pId) throws Exception;
	
	public AutorizacionSolicitudSuministro updateAutorizacionSolicitudSuministro (AutorizacionSolicitudSuministro pAutorizacion) throws Exception;

	public AutorizacionSolicitudSuministro addAutorizacionSolicitudSuministro (AutorizacionSolicitudSuministro pAutorizacion) throws Exception;

	public SolicitudSuministro firmarSolicitudSuminstro(SolicitudSuministro pSolicitud, FirmaPermisoSolicitud pFirma)
			throws TrascenderException;

	public CuentaRfr getCuentaRfr(LineaSolicitudSuministro pLinea);

	public void updateCuentaRfr(SolicitudSuministro pSolicitudSuministro);

	public void finalizarSolicitud(SolicitudSuministro pSolicitud) throws TrascenderException;

	public List<LineaSolicitudSuministro> findListaLineasSolicitudSuministro(boolean filtrarPorCodCiiu, boolean filtrarPorCategoria, List<Proveedor> pListaProveedores, Bien pBien, SolicitudSuministro pSolicitud) throws TrascenderException;

	public EstadoSolicitudSuministro addEstadoSolicitudSuministro(EstadoSolicitudSuministro pEstadoSolSum) throws TrascenderComprasException;

	public void updateEstadoSolicitudSuministro(EstadoSolicitudSuministro pEstadoSolSum) throws TrascenderComprasException;

	public void deleteEstadoSolicitudSuministro(EstadoSolicitudSuministro pEstadoSolSum) throws TrascenderComprasException;

	public FiltroEstadoSolicitudSuministro findListaEstadoSolSum(FiltroEstadoSolicitudSuministro pFiltro);

	public List<EstadoSolicitudSuministro> findListaEstadoSolSumFinal();
	
	public List<EstadoSolicitudSuministro> getListaEstadosFinalizacion(Usuario pUsuario, SolicitudSuministro pSolicitud);

	public boolean validarOperarSolicitudesUrgentes(Area pArea, Usuario pUsuario);
	
	public List<LineaOrdenCompra> getListaLineaOrdenCompraPorSolicitud(SolicitudSuministro pSolicitudSuministro);
	
	public AutorizacionSolicitudSuministro validarFirma(SolicitudSuministro pSolicitudSuministro, Usuario pUsuario) throws TrascenderException;
}
