/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.business.interfaces;

import javax.ejb.Local;

import com.trascender.compras.recurso.filtros.FiltroCondicionCompra;
import com.trascender.compras.recurso.filtros.FiltroOrdenCompra;
import com.trascender.compras.recurso.filtros.FiltroTipoOrdenCompra;
import com.trascender.compras.recurso.filtros.FiltroUsuarioFirmante;
import com.trascender.compras.recurso.persistent.suministros.OrdenCompra;
import com.trascender.compras.recurso.persistent.suministros.Proveedor;
import com.trascender.compras.recurso.persistent.suministros.UsuarioAutorizadorOrdenCompra;
import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.FirmaPermiso;

@Local
public interface BusinessOrdenCompraLocal
{
	
	public static final String JNDI_NAME = "BusinessOrdenCompraLocal";
	
   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra addTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public FiltroTipoOrdenCompra findListaTiposOrdenesCompra( FiltroTipoOrdenCompra pFiltro ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra updateTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public void deleteTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra findTipoOrdenCompraByID( long pId ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.CondicionCompra addCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.CondicionCompra updateCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public void deleteCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public FiltroCondicionCompra findListaCondicionCompra( FiltroCondicionCompra pFiltro) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra addOrdenCompra( com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra ) throws java.lang.Exception;

   /**
    * Business method
    */
   public FiltroOrdenCompra findListaOrdenCompra(FiltroOrdenCompra pFiltro ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra findOrdenCompraByID( long pID ) throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra updateOrdenCompra( com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra ) throws java.lang.Exception;
   
   /**
    * Business method 
    */
   public OrdenCompra firmarOrdenCompra(OrdenCompra pOrdenCompra, FirmaPermiso pFirmaPermiso) throws java.lang.Exception;
   
   public void finalizarOrdenCompra(OrdenCompra pOrdenCompra) throws TrascenderException;
   
   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra findTipoOrdenCompraByMonto( java.lang.Double pMonto ) throws java.lang.Exception;
   
   public void transferirOrdenCompra(OrdenCompra pOrden, Proveedor pProveedor, String pComentario) throws Exception;

   
   	public UsuarioAutorizadorOrdenCompra addUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public UsuarioAutorizadorOrdenCompra updateUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public void deleteUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public FiltroUsuarioFirmante findListaUsuariosFirmantes(FiltroUsuarioFirmante pFiltro) throws Exception;
	
	public UsuarioAutorizadorOrdenCompra getUsuarioFirmantePorId(long pIdUsuarioFirmante);
}
