/*
 * Generated by XDoclet - Do not edit!
 */

package com.trascender.compras.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.compras.recurso.filtros.FiltroBien;
import com.trascender.compras.recurso.filtros.FiltroTipoBien;
import com.trascender.compras.recurso.filtros.FiltroUnidad;
import com.trascender.compras.recurso.persistent.suministros.Bien;
import com.trascender.compras.recurso.persistent.suministros.BienProvisto;
import com.trascender.compras.recurso.persistent.suministros.TipoBien;
import com.trascender.compras.recurso.persistent.suministros.Unidad;
import com.trascender.framework.recurso.transients.AuxIdEntidad;

@Local
public interface BusinessBienLocal {

	public static final String JNDI_NAME = "BusinessBienLocal";

	/**
	 * Business method
	 */
	// public com.trascender.compras.recurso.persistent.suministros.GrupoBien addGrupoBien( com.trascender.compras.recurso.persistent.suministros.GrupoBien
	// pGrupoBien ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	// public com.trascender.compras.recurso.persistent.suministros.GrupoBien findGrupoBienesPorNombre( java.lang.String pNombre ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	// public java.util.List findListaGrupoBienesPorNodo( com.trascender.compras.recurso.persistent.suministros.GrupoBien pNodo ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	// public com.trascender.compras.recurso.persistent.suministros.GrupoBien updateGrupoBien( com.trascender.compras.recurso.persistent.suministros.GrupoBien
	// pNodo ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	// public void deleteGrupoBien( com.trascender.compras.recurso.persistent.suministros.GrupoBien pNodo ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	// public java.util.List getListadoGrupoBienes( ) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.Bien addBien(com.trascender.compras.recurso.persistent.suministros.Bien pBien) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public FiltroBien getListadoBienes(FiltroBien pFiltro) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.Bien updateBien(com.trascender.compras.recurso.persistent.suministros.Bien pBien) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public BienProvisto updateBienProvisto(BienProvisto pBienProvisto) throws Exception;

	/**
	 * Business method
	 */
	public void deleteBien(com.trascender.compras.recurso.persistent.suministros.Bien pBien) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.Bien restoreBien(com.trascender.compras.recurso.persistent.suministros.Bien pBien) throws java.lang.Exception;

	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.Bien findBienByID(long pIdBien) throws java.lang.Exception;

	/**
	 * Business method
	 * 
	 * @param pGrupo
	 * @param pBien
	 * @return
	 * @throws Exception
	 */
	public List<Bien> validarNombreBien(Bien pBien) throws Exception;

	/**
	 * Business method
	 */
	public Unidad addUnidad(Unidad pUnidad) throws Exception; // Marina

	/**
	 * Business method
	 */
	public Unidad updateUnidad(Unidad pUnidad) throws Exception; // Marina

	/**
	 * Business method
	 */
	public void deleteUnidad(Unidad pUnidad) throws Exception; // Marina

	/**
	 * Business method
	 */
	public FiltroUnidad findListaUnidad(FiltroUnidad filtro) throws Exception; // Marina

	/**
	 * Business method
	 */

	public Unidad getUnidadByID(Long pIDUnidad) throws Exception; // Marina

	public TipoBien getTipoBienByID(Long pIDTipoBien) throws Exception;

	public TipoBien addTipoBien(TipoBien pTipoBien) throws Exception;

	public TipoBien updateTipoBien(TipoBien pTipoBien) throws Exception;

	public void deleteTipoBien(TipoBien pTipoBien) throws Exception;

	public FiltroTipoBien findListaTipoBien(FiltroTipoBien filtro) throws Exception;

	public FiltroBien findListaBien(FiltroBien filtro) throws Exception;

	public List<AuxIdEntidad> findListaAuxIdBien(String cadena) throws Exception;
}