/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.business.interfaces;

import javax.ejb.Local;

/**
 * Remote interface for ControlCompras.
 */
@Local
public interface ControlCompras
{
	public static final String JNDI_NAME = "ejb/ControlCompras";
   /**
    * Business method
    */
   public boolean generateGrupoRecusosCompras(  )
      throws java.lang.Exception, java.rmi.RemoteException;

}
