/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.system.interfaces;

import javax.ejb.Remote;

@Remote
public interface SystemImpresionTicketCaja
{
	
	public static final String JNDI_NAME = "ejb/SystemImpresionTicketCaja/remote";

   public void setLlave( long llave )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    * @param pIdTicketCaja
    * @throws com.trascender.framework.exception    */
   public void getReporteTicketCaja( java.lang.Long pIdTicketCaja )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

}
