/*
 * Generated by XDoclet - Do not edit!
 */

package com.trascender.framework.system.interfaces;

import java.util.List;

import javax.ejb.Remote;

import com.trascender.framework.exception.TrascenderFrameworkException;
import com.trascender.framework.recurso.filtros.FiltroPersonaFisica;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.transients.AuxIdEntidad;

/**
 * Remote interface for SystemPersonaFisica.
 */
@Remote
public interface SystemPersonaFisica {

	public static final String JNDI_NAME = "ejb/SystemPersonaFisica/remote";

	/**
	 * Permite agregar una persona f�sica
	 * 
	 * @param Persona
	 *            f�sica que se desea agregar, �sta no debe estar registrada
	 * @throws TrascenderFrameworkException
	 *             , Exception Business method
	 */
	public void addPersonaFisica(com.trascender.framework.recurso.persistent.PersonaFisica pPersonaFisica) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	/**
	 * Permite actualizar los datos ingresados de una persona f�sica
	 * 
	 * @param Persona
	 *            f�sica que se desea actualizar, �sta debe estar registrada Business method
	 */
	public void updatePersonaFisica(com.trascender.framework.recurso.persistent.PersonaFisica pPersonaFisica) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	/**
	 * Business method
	 * 
	 * @throws TrascenderFrameworkException
	 */
	public void removePersonaFisica(com.trascender.framework.recurso.persistent.PersonaFisica pPersona) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public void restorePersonaFisica(com.trascender.framework.recurso.persistent.PersonaFisica pPersona) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	/**
	 * Business method
	 * 
	 * @param pCuil
	 *            cuil
	 * @param pNombre
	 *            nombre de la persona fisica
	 * @param pApellido
	 *            aplellido de la persona f�sica
	 * @param pDomicilioPostal
	 *            domicilio postal (no funciona)
	 * @param pFechaNacimiento
	 *            fecha de nacimiento
	 * @param pEdad
	 *            edad de la persona
	 * @param pSexo
	 *            sexo de la persona
	 * @param pTelefono
	 *            telefono de la persona
	 * @param pCelular
	 *            celular de la persona
	 * @param pEmail
	 *            email de la persona
	 * @param pEstado
	 *            estado en que se encuentra la persona
	 */
	public FiltroPersonaFisica findPersonaFisica(FiltroPersonaFisica pFiltro) throws com.trascender.framework.exception.TrascenderException;

	/**
	 * Business method
	 * 
	 * @throws TrascenderFrameworkException
	 *             (14) en caso que la persona no exista
	 */
	public com.trascender.framework.recurso.persistent.PersonaFisica getPersonaFisicaPorCuim(java.lang.String pCuim) throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public void setLlave(long pLlave) throws java.rmi.RemoteException;

	/**
	 * Recupera el listado completo de personas f�sicas Business method
	 * 
	 * @throws TrascenderFrameworkException
	 *             (12) no se puede recuperar el listado de personas f�sicas
	 */
	public java.util.List getListadoPersonasFisicas(java.lang.String pEstado) throws com.trascender.framework.exception.TrascenderFrameworkException, java.rmi.RemoteException;

	/**
	 * Business method
	 * 
	 * @throws TrascenderFrameworkException
	 */
	public java.util.List getListadoPersonasFisicas() throws com.trascender.framework.exception.TrascenderFrameworkException, java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public com.trascender.framework.recurso.persistent.PersonaFisica getPersonaFisicaPorId(long pId) throws com.trascender.framework.exception.TrascenderFrameworkException,
			java.rmi.RemoteException;

	public Persona getPersonaPorId(long pId) throws com.trascender.framework.exception.TrascenderFrameworkException, java.rmi.RemoteException;

	public List<AuxIdEntidad> findListaAuxIdPersona(String cadena) throws com.trascender.framework.exception.TrascenderException;
}
