/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.framework.system.interfaces;

import java.util.List;

import javax.ejb.Remote;

import com.trascender.framework.recurso.filtros.FiltroPersonaJuridica;
import com.trascender.framework.recurso.persistent.dinamicos.AtributoDinamico;

/**
 * Remote interface for SystemPersonaJuridica.
 */
@Remote
public interface SystemPersonaJuridica {
	
	public static final String JNDI_NAME = "ejb/SystemPersonaJuridica/remote";
	
   /**
    * Business method
    */
   public void addPersonaJuridica( com.trascender.framework.recurso.persistent.PersonaJuridica pPersonaJuridica )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void updatePersonaJuridica( com.trascender.framework.recurso.persistent.PersonaJuridica pPersonaJuridica )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void removePersonaJuridica( com.trascender.framework.recurso.persistent.PersonaJuridica pPersonaJuridica )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void restorePersonaJuidica( com.trascender.framework.recurso.persistent.PersonaJuridica pPersonaJuridica )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public FiltroPersonaJuridica findPersonaJuridica(FiltroPersonaJuridica filtro )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.framework.recurso.persistent.PersonaJuridica getPersonaJuridicaPorCuit( java.lang.String pCuit )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

   /**
    * Recupera una persona juridica por id
    * @param pId
    * @return nulo en caso que no encuentre nada
    */
   public com.trascender.framework.recurso.persistent.PersonaJuridica getPersonaJuridicaPorId( long pId )
      throws java.rmi.RemoteException;

}
