/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.framework.system.interfaces;

import javax.ejb.Local;

/**
 * Local interface for SystemLogSeguridad.
 */
@Local
public interface SystemLogSeguridadLocal {
	
	public static final String JNDI_NAME = "ejb/SystemLogSeguridad/local";	

   public void registrarLogSeguridad( com.trascender.framework.recurso.transients.Conexion pConexion,java.lang.String pNombreUsuario,java.lang.String pNombreRecurso,java.lang.Boolean pHabilitado,com.trascender.framework.recurso.persistent.Permiso.Accion pAccion ) throws com.trascender.framework.exception.TrascenderException;

   /**
    * Recupera el listado de logs de seguridad seg�n los par�metros
    * @param pUsuario
    * @return 
    * @throws Exception
    */
   public java.util.List getListaLogsSeguridad( java.util.Date pFechaDesde,java.util.Date pFechaHasta,com.trascender.framework.recurso.persistent.Usuario pUsuario ) throws java.lang.Exception;

}
