/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.catastro.business.interfaces;

import javax.ejb.Local;

import com.trascender.catastro.recurso.filtros.FiltroCategoria;
import com.trascender.catastro.recurso.filtros.FiltroTipoConstruccion;
import com.trascender.catastro.recurso.filtros.FiltroValorBasicoMejora;
import com.trascender.catastro.recurso.persistent.TipoConstruccion;
import com.trascender.catastro.recurso.persistent.ValorBasicoMejora;

/**
 * Local interface for BusinessCodigosCatastrales.
 */

@Local
public interface BusinessCodigosCatastralesLocal
{
	
	public static final String JNDI_NAME="BusinessCodigosCatastralesLocal";
   
	/**
    * Agrega un tipo de construcci�n
    * @param pTipoConstruccion tipo de construcciona a agregar
    */
   public com.trascender.catastro.recurso.persistent.TipoConstruccion addTipoConstruccion( com.trascender.catastro.recurso.persistent.TipoConstruccion pTipoConstruccion ) 
   throws java.lang.Exception;

   /**
    * Actualiza el tipo de construccion
    * @param pTipoConstruccion tipo de construccion a actualizar
    */
   public com.trascender.catastro.recurso.persistent.TipoConstruccion updateTipoConstruccion( com.trascender.catastro.recurso.persistent.TipoConstruccion pTipoConstruccion ) 
   throws java.lang.Exception;

   /**
    * Recupera un listado de tipos de cosntrucciones
    * @param pIdTipoConstruccion n�mero de identificaci�n del tipo de construcci�n
    * @param pNombre nombre del tipo de construcci�n, solo es verificado si el id es nulo
    * @param estado true=ACTIVO false=ELIMINADO
    * @return List listado con tipos de construcci�n
    */
   @SuppressWarnings("unchecked")
   public FiltroTipoConstruccion findTiposConstrucciones(FiltroTipoConstruccion pFiltro);

   /**
    * Agrega una nueva categoria
    */
   public com.trascender.catastro.recurso.persistent.Categoria addCategoria( com.trascender.catastro.recurso.persistent.Categoria pCategoria ) 
   throws java.lang.Exception;

   /**
    * Actualiza los datos de una categor�a
    */
   public com.trascender.catastro.recurso.persistent.Categoria updateCategoria( com.trascender.catastro.recurso.persistent.Categoria pCategoria ) 
   throws java.lang.Exception;

   /**
    * recupera un listado de categorias
    * @param pCodigoCategoria c�digo de la categor�a
    * @param pEstado estado de la categor�a
    * @param pTipoConstruccion tipo de cosntrucci�n de la categor�a
    */
   @SuppressWarnings("unchecked")
   public FiltroCategoria findListaCategorias(FiltroCategoria pFiltro) 
   throws java.lang.Exception;

   /**
    * Recupera una categor�a por id
    */
   public com.trascender.catastro.recurso.persistent.Categoria getCategoriaPorId( long pIdCategoria ) ;
   
   /**
    * Recupera un tipo de construccion por id
    */
   public TipoConstruccion getTipoConstruccionPorId(long pIdTipoConstruccion) ;
   
   /**
    * Recupera un valor basico de mejora por id
    */
   public ValorBasicoMejora getValorBasicoMejoraPorId(long pIdValorBasicoMejora) ;
   
   /**
    * agrega un coeficiente de depreciacion
    */
   public com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion addCoeficienteDepreciacion( com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion pCoeficienteDepreciacion ) 
   throws java.lang.Exception;

   /**
    * Actualiza los datos de un coeficiente de depreciaci�n
    */
   public com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion updateCoeficienteDepreciacion( com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion pCoeficienteDepreciacion ) 
   throws java.lang.Exception;

   /**
    * Elimina un coeficiente de depreciacion de la tabla
    */
   public void deleteCoeficienteDepreciacion( com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion pCoeficienteDepreciacion ) 
   throws java.lang.Exception;

   /**
    * REcupera un coeficiente de depreciaci�n seg�n los a�os de antig�edad y la categoria
    */
   public com.trascender.catastro.recurso.persistent.CoeficienteDepreciacion findCoeficienteDepreciacion( java.lang.Integer pAniosAntiguedad,com.trascender.catastro.recurso.persistent.Categoria pCategoria ) 
   throws java.lang.Exception;

   /**
    * Recupera un listado de coeficientes de depreciacion de los 75 a�os
    * @param pCategoria categoria a la que pertenecen los coeficientes de depreciacion, no puede ser nula
    */
   @SuppressWarnings("unchecked")
   public java.util.List findListaCoeficientesDepreciacion( com.trascender.catastro.recurso.persistent.Categoria pCategoria ) 
   throws java.lang.Exception;

   /**
    * Agrega un valor b�sico por mejora
    */
   public com.trascender.catastro.recurso.persistent.ValorBasicoMejora addValorBasicoMejora( com.trascender.catastro.recurso.persistent.ValorBasicoMejora pValorBasicoMejora ) 
   throws java.lang.Exception;

   /**
    * Actualiza los datos de una valor b�sico por mejora
    */
   public com.trascender.catastro.recurso.persistent.ValorBasicoMejora updateValorBasicoMejora( com.trascender.catastro.recurso.persistent.ValorBasicoMejora pValorBasicoMejora ) 
   throws java.lang.Exception;

   /**
    * Elimina un valor b�sico por mejora
    */
   public void deleteValorBasicoMejora( com.trascender.catastro.recurso.persistent.ValorBasicoMejora pValorBasicoMejora ) 
   throws java.lang.Exception;

   /**
    * Recupera un listado de valores b�sicos por mejora
    */
   @SuppressWarnings("unchecked")
   public FiltroValorBasicoMejora findListaValoresBasicosMejora(FiltroValorBasicoMejora pFiltro) 
   throws java.lang.Exception;

   /**
    * Recupera un valor b�sico por mejora
    */
   public com.trascender.catastro.recurso.persistent.ValorBasicoMejora findValorBasicoMejora( java.lang.Integer pAnio,com.trascender.catastro.recurso.persistent.Categoria pCategoria ) 
   throws java.lang.Exception;

   /**
    * Almacena un listado de coeficientes de depreciaci�n
    * @param listado listado de coeficientes de depreciaci�n a almacenar
    * @throws Exception
    */
   @SuppressWarnings("unchecked")
   public void saveListadoCoeficienteDepreciacion( java.util.List listado ) 
   throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.catastro.recurso.persistent.VolanteCatastral updateVolanteCatastral( com.trascender.catastro.recurso.persistent.VolanteCatastral pVolanteCatastral ) 
   throws java.lang.Exception;

   /**
    * Business method
    */
   public void deleteVolanteCatastral( com.trascender.catastro.recurso.persistent.VolanteCatastral pVolanteCatastral ) 
   throws java.lang.Exception;

}
