/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.catastro.business.interfaces;

import java.util.Date;
import java.util.List;

import javax.ejb.Local;

import com.trascender.catastro.recurso.filtros.FiltroParcela;
import com.trascender.catastro.recurso.filtros.FiltroTituloPropiedad;
import com.trascender.catastro.recurso.persistent.Parcela;
import com.trascender.catastro.recurso.persistent.TituloPropiedad;
import com.trascender.catastro.recurso.persistent.TituloPropiedadParcelario;
import com.trascender.framework.recurso.persistent.Persona;

/**
 * Local interface for BusinessRegistroPropiedad.
 */
@Local
public interface BusinessRegistroPropiedadLocal
{
	public static final String JNDI_NAME="BusinessRegistroPropiedadLocal/local";
   /**
    * Business method
    * @throws Exception
    */
   public TituloPropiedadParcelario addTituloPropiedad(TituloPropiedadParcelario pTituloPropiedad ) throws Exception;

   /**
    * Business method
    */
   public TituloPropiedadParcelario updateTituloPropiedad(TituloPropiedadParcelario pTituloPropiedad ) 
   throws java.lang.Exception;

   /**
    * Business method
    */
   @SuppressWarnings("unchecked")
   public FiltroTituloPropiedad findTituloPropiedad(FiltroTituloPropiedad filtro) throws Exception;
   
//   @SuppressWarnings("unchecked")
//   public FiltroParcela findTituloPropiedad(FiltroParcela filtro) throws Exception;

   /**
    * Recupera el primer propietario de una parcela
    * @param pParcela parcela a la que se quiere recuperar un propietario
    * @return 
    * @throws Exception
    */
   public java.lang.Long getIdPropietario( com.trascender.catastro.recurso.persistent.Parcela pParcela ) 
   throws java.lang.Exception;

   /**
    * Recupera la persona que es propietaria de la parcela
    * @param pParcela
    * @return 
    * @throws Exception
    */
   public com.trascender.framework.recurso.persistent.Persona getPropietario(com.trascender.catastro.recurso.persistent.Parcela pParcela ) 
   throws java.lang.Exception;


   public TituloPropiedad getTituloPropiedadPorId( java.lang.Long pIdTituloPropiedad ) 
   throws java.lang.Exception;

}
