/*
 * Generated by XDoclet - Do not edit!
 */

package com.trascender.saic.system.interfaces;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.Remote;

import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.transients.Calendario;
import com.trascender.habilitaciones.recurso.persistent.CuotaLiquidacion;
import com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS;
import com.trascender.habilitaciones.recurso.persistent.PeriodoLiquidacion;
import com.trascender.habilitaciones.recurso.persistent.tasaMenor.PlantillaDocumentoTasaMenor;
import com.trascender.habilitaciones.recurso.persistent.tasaMenor.RegistroValuadoTasaMenor;
import com.trascender.saic.recurso.filtros.FiltroDDJJSHPS;
import com.trascender.saic.recurso.filtros.FiltroValorMedidor;

/**
 * Remote interface for SystemRegistroValuado.
 * 
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Remote
public interface SystemRegistroValuado {

	public static final String JNDI_NAME = "ejb/SystemRegistroValuado/remote";

	public DeclaracionJuradaSHPS getNuevaDDJJSHPS(Persona pPersona, CuotaLiquidacion pCuota, String pNroInscripcion, ArrayList pListaAtributosDinamicos) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

	public FiltroDDJJSHPS getListaDDJJSHPS(FiltroDDJJSHPS pFiltro) throws TrascenderException, RemoteException;

	public DeclaracionJuradaSHPS getDDJJSHPSporId(long pIdDeclaracion) throws TrascenderException, RemoteException;

	public void setLlave(long pLlave) throws java.rmi.RemoteException;

	public void addDDJJSHPS(DeclaracionJuradaSHPS pDDJJSHPS) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
	
	public DeclaracionJuradaSHPS addDDJJSHPSParaLiquidar(DeclaracionJuradaSHPS pDDJJSHPS) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

	public void updateDDJJSHPS(com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS pDeclaracionJuradaSHPS)
			throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

	public void deleteDDJJSHPS(com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS pDeclaracionJuradaSHPS)
			throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

	public java.util.List getListaNuevasMedidasServiciosOSP(com.trascender.catastro.recurso.persistent.Calle pCalle, CuotaLiquidacion pCuota,
			com.trascender.habilitaciones.recurso.persistent.osp.ServicioOSP pServicio, String pCodigoMedidor) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	public void updateValorMedidor(com.trascender.habilitaciones.recurso.persistent.ValorMedidor pValorMedidor) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	public void addListaValorMedidor(java.util.List pValoresMedidores) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

	public com.trascender.habilitaciones.recurso.persistent.ValorMedidor getValorMedidorPorId(long pIdRegistroValuado) throws com.trascender.framework.exception.TrascenderException,
			java.rmi.RemoteException;

	public FiltroValorMedidor findListaValoresMedidor(FiltroValorMedidor pFiltro) throws TrascenderException, RemoteException;

	public List<RegistroValuadoTasaMenor> findListaRegistrosValuadosTasaMenor(Persona pPersona, CuotaLiquidacion pCuota, PeriodoLiquidacion pPeriodo, Calendario pCalendario,
			PlantillaDocumentoTasaMenor pPlantilla) throws TrascenderException;

	public List<RegistroValuadoTasaMenor> generarRegistrosTasaMenor(Persona pPersona, CuotaLiquidacion pCuota, PlantillaDocumentoTasaMenor pPlantilla) throws TrascenderException;

	public void addRegistrosValuadosTasaMenor(List<RegistroValuadoTasaMenor> pListaRegistrosValuados) throws TrascenderException;

	public void updateRegistroValuadoTasaMenor(RegistroValuadoTasaMenor pRegistroValuado) throws TrascenderException;

	public void deleteRegistroValuadoTasaMenor(RegistroValuadoTasaMenor pRegistroValuadoTasaMenor) throws Exception;

	public RegistroValuadoTasaMenor getRegistroValuadoTasaMenorPorId(long pId);

	public java.util.List findListaPagoSellado(com.trascender.framework.recurso.persistent.Persona pPersona, com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion,
			java.lang.Boolean pPagado) throws java.lang.Exception, java.rmi.RemoteException;
}
