/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.saic.system.interfaces;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.ejb.Remote;

import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.persistent.Usuario;
import com.trascender.framework.recurso.transients.Periodo;
import com.trascender.habilitaciones.recurso.persistent.TipoObligacion;
import com.trascender.saic.recurso.persistent.LiquidacionTasa;
import com.trascender.saic.recurso.persistent.ParametroValuadoAlicuota;
import com.trascender.saic.recurso.persistent.RegistroDeuda.EstadoRegistroDeuda;
import com.trascender.saic.recurso.persistent.RegistroDeuda.TipoDeuda;


/**
 * Remote interface for SystemReliquidacion.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Remote
public interface SystemReliquidacion
{
	 public static final String JNDI_NAME="ejb/SystemReliquidacion/remote";

   public List reliquidarObligacion( 
		   com.trascender.saic.recurso.persistent.LiquidacionTasa pLiquidacionTasa,
		   java.util.Date pFechaReLiquidacion,
		   List<String> pListaNombresNuevosParametrosValuados,
		   List<ParametroValuadoAlicuota> pListaNuevosParametrosAlicuotas,
		   Map<String, Object> pMapaValoresFijos,
		   com.trascender.framework.recurso.persistent.DigestoMunicipal pDigestoMunicipal,
		   boolean pAplicarIntereses
		   ) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   public List reliquidarObligacion( 
		   com.trascender.saic.recurso.persistent.LiquidacionTasa pLiquidacionTasa,
		   java.util.Date pFechaReLiquidacion,java.util.Date pFechaNuevoVencimiento,
		   boolean pAplicarIntereses
		  // com.trascender.framework.recurso.persistent.DigestoMunicipal pDigestoMunicipal
		   ) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public List findListaRegistrosDeudaContribuyente(
		   Persona pPersona, 
		   TipoDeuda pTipoDeuda,
		   Periodo pPeriodo, 
		   EstadoRegistroDeuda pEstadoRegistroDeuda,
		   TipoObligacion pTipoObligacion,
		   com.trascender.catastro.recurso.persistent.Parcela pParcela
		   ) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public com.trascender.saic.recurso.persistent.Reliquidacion getReliquidacionPorId(long pId) 
   	  throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public com.trascender.saic.recurso.persistent.Reliquidacion getReliquidacionPorIdNuevaDeuda(long pIdDeuda)
	throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;
   
   public LiquidacionTasa calcularIntereses(LiquidacionTasa pLiquidacionTasa, 
			Date pFecha, boolean pAplicarInteres, 
			boolean guardarCambios) throws Exception;
   
   public LiquidacionTasa notificar(LiquidacionTasa pLiquidacionTasa, Date fechaNotificacion,
		   Date fechaApremio, String comentario) throws TrascenderException;
   
	public void notificar(List<LiquidacionTasa> listaLiquidaciones,
			Date fechaNotificacion, Date fechaApremio, String comentario) throws TrascenderException;

}
