/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.saic.system.interfaces;

import java.util.List;
import java.util.Set;

import javax.ejb.Remote;

import com.trascender.catastro.recurso.persistent.Parcela;
import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.transients.Periodo;
import com.trascender.habilitaciones.recurso.persistent.Obligacion;
import com.trascender.habilitaciones.recurso.persistent.TipoObligacion;
import com.trascender.saic.recurso.filtros.FiltroLiquidacionTasaRefer;
import com.trascender.saic.recurso.filtros.FiltroPlantillaPlanDePago;
import com.trascender.saic.recurso.persistent.LiquidacionTasa;
import com.trascender.saic.recurso.persistent.PlantillaPlanDePago;
import com.trascender.saic.recurso.persistent.RegistroDeuda.EstadoRegistroDeuda;
import com.trascender.saic.recurso.references.LiquidacionTasaRefer;
import com.trascender.saic.recurso.transients.LiquidacionTasaAgrupada;

/**
 * Remote interface for SystemEstadoCuentaContribuyente.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Remote
public interface SystemEstadoCuentaContribuyente{

	 public static final String JNDI_NAME="ejb/SystemEstadoCuentaContribuyente/remote";
	 
   public java.util.List getListaObligacionesContribuyente(Long pIdTramite, com.trascender.framework.recurso.persistent.Persona pPersona,com.trascender.habilitaciones.recurso.persistent.Obligacion.Estado pEstadoObligacion )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public java.util.List getListaObligacionesContribuyente(com.trascender.framework.recurso.persistent.Persona pPersona, com.trascender.habilitaciones.recurso.persistent.Obligacion.Estado pEstadoObligacion)
   		throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   public java.util.List getListaRegistrosDeudaObligacion(com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion, EstadoRegistroDeuda pEstadoRegistroDeuda, String pEstado, Periodo pPeriodo) 
   		throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public java.util.List getListaDeudasContribuyente( com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   public java.util.List getListaDeudasContribuyente( java.util.List pListaObligaciones )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   public java.util.List getListaEstadosCuentaContribuyente(Persona pPersona, Obligacion.Estado pEstadoObligacion) throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   
   /**
    * Recupera el listado de DocHabEspecializados de un contribuyente
    * @param pPersona contribuyente
    * @return 
    * @throws Exception
    */
   public java.util.List getListaDocEspecializadosContribuyente(Persona pPersona) 
   		throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;
   		
   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;
   
   public LiquidacionTasaAgrupada inicializarLiquidacionTasaAgrupada(LiquidacionTasaRefer pLiquidacion);
   
   public FiltroLiquidacionTasaRefer findListaLiquidacionTasaRefer(FiltroLiquidacionTasaRefer pFiltro) throws Exception;
   
   public void addPlantillaPlanDePago(PlantillaPlanDePago plantilla) throws TrascenderException;
	
   public void updatePlantillaPlanDePago(PlantillaPlanDePago plantilla) throws TrascenderException;
	
   public void deletePlantillaPlanDePago(PlantillaPlanDePago plantilla) throws TrascenderException;
	
   public FiltroPlantillaPlanDePago findListaPlantillaPlanDePago(FiltroPlantillaPlanDePago filtro) throws TrascenderException;
}
