/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.system.interfaces;

import javax.ejb.Remote;

import com.trascender.habilitaciones.recurso.persistent.FiltroObligacionTGI;
import com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI;

@Remote
public interface SystemDocumentoTGI {
	
	public static final String JNDI_NAME = "ejb/SystemDocumentoTGI/remote";
	
   /**
    * Agrega un documento TGI al registro
    * @param pDocumentoTGI
    * @return 
    * @throws Exception
    */
   public com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI addDocumentoTGI( com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI pDocumentoTGI )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Actualiza los datos de un documento TGI
    * @param pDocumentoTGI
    * @return 
    * @throws Exception
    */
   public com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI updateDocumentoTGI( com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI pDocumentoTGI )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Elimina un documento tgi
    * @param pDocumentoTGI
    * @throws Exception
    */
   public void deleteDocumentoTGI( DocumentoTGI pDocumentoTGI )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Recupera un listado de documentos de tgi
    * @param pPersona
    * @return 
    * @throws Exception
    */
   @SuppressWarnings("unchecked")
   public FiltroObligacionTGI findListaDocumentoTGI(FiltroObligacionTGI pFlitro)
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   public com.trascender.habilitaciones.recurso.persistent.tgi.DocumentoTGI getDocumentoTGI( com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion )
      throws com.trascender.framework.exception.TrascenderException, java.rmi.RemoteException;

   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

}
