/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.system.interfaces;

import javax.ejb.Remote;

@Remote
public interface SystemDocumentoTransito {
	
	public static final String JNDI_NAME = "ejb/SystemDocumentoTransito/remote";
	

   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

}
