/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.system.interfaces;

import java.rmi.RemoteException;

import javax.ejb.Remote;

import com.trascender.framework.exception.TrascenderException;
import com.trascender.habilitaciones.recurso.filtros.FiltroRubroSHPS;
import com.trascender.habilitaciones.recurso.persistent.RegAlicuota;
import com.trascender.habilitaciones.recurso.persistent.shps.Rubro;

@Remote
public interface SystemAlicuota {
	
	public static final String JNDI_NAME = "ejb/SystemAlicuota/remote";

   public void setLlave( long pLlave ) throws RemoteException;

   public RegAlicuota addRegistroAlicuota(RegAlicuota pRegistroAlicuota ) throws TrascenderException, RemoteException;

   public RegAlicuota updateRegistroAlicuota(RegAlicuota pRegistroAlicuota) throws TrascenderException, RemoteException;

   public void deleteRegistroAlicuota( RegAlicuota pRegistroAlicuota ) throws TrascenderException, java.rmi.RemoteException;

   public FiltroRubroSHPS findListaRubros(FiltroRubroSHPS pFiltro) throws TrascenderException, RemoteException;
   
   public RegAlicuota getRegistroAlicuotaPorId(long pId) throws TrascenderException, RemoteException;
   
   public Rubro getRubroPorId(long pId) throws TrascenderException, RemoteException;
}
