/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.system.interfaces;

import javax.ejb.Remote;

import com.trascender.compras.recurso.filtros.FiltroFacturaServicio;

/**
 * Remote interface for SystemAdministracionFacturaServicio
 */

@Remote
public interface SystemAdministracionFacturaServicio 
	{
	
	public static final String JNDI_NAME = "ejb/SystemAdministracionFacturaServicio/remote";
	
	/**
	 * Business method
	 */
	public void setLlave(long pLlave) throws java.rmi.RemoteException;
	
	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio addFacturaServicio(com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio)
		throws java.lang.Exception, java.rmi.RemoteException;
	
	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio updateFacturaServicio(com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio)
		throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public void deleteFacturaServicio(com.trascender.compras.recurso.persistent.suministros.FacturaServicio pFacturaServicio)
		throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public com.trascender.compras.recurso.persistent.suministros.FacturaServicio getFacturaServicioPorId(long pId)
		throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * Business method
	 */
	public FiltroFacturaServicio findListaFacturasServicio(FiltroFacturaServicio pFiltro)
		throws java.lang.Exception,java.rmi.RemoteException;
	
}
