/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.system.interfaces;

import java.rmi.RemoteException;

import javax.ejb.Remote;

import com.trascender.compras.recurso.filtros.FiltroOrdenCompra;
import com.trascender.compras.recurso.filtros.FiltroTipoOrdenCompra;
import com.trascender.compras.recurso.filtros.FiltroUsuarioFirmante;
import com.trascender.compras.recurso.persistent.suministros.OrdenCompra;
import com.trascender.compras.recurso.persistent.suministros.Proveedor;
import com.trascender.compras.recurso.persistent.suministros.UsuarioAutorizadorOrdenCompra;
import com.trascender.framework.exception.TrascenderException;

@Remote
public interface SystemAdministracionOrdenCompra
{
	
	public static final String JNDI_NAME = "ejb/SystemAdministracionOrdenCompra/remote";

   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra addTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public FiltroTipoOrdenCompra findListaTiposOrdenesCompra(FiltroTipoOrdenCompra pFiltro )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra updateTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void deleteTipoOrdenCompra( com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra pTipoOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.TipoOrdenCompra findTipoOrdenCompraByID( long pId )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra addOrdenCompra( com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public FiltroOrdenCompra findOrdenCompra(FiltroOrdenCompra pFiltro )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra updateOrdenCompra( com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method 
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra firmarOrdenCompra(
			com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra) throws java.lang.Exception, java.rmi.RemoteException;
   
   /**
    * Business method
    */
   public void finalizarOrdenCompra( com.trascender.compras.recurso.persistent.suministros.OrdenCompra pOrdenCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.OrdenCompra findOrdenCompraByID( long pID )
      throws java.lang.Exception, java.rmi.RemoteException;


   public void transferirOrdenCompra(OrdenCompra pOrden, Proveedor pNuevoProveedor, String pComentario) throws Exception, RemoteException;
   
   public UsuarioAutorizadorOrdenCompra addUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public UsuarioAutorizadorOrdenCompra updateUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public void deleteUsuarioAutorizadorOrdenCompra(UsuarioAutorizadorOrdenCompra pUsuarioAutorizador) throws Exception;
	
	public FiltroUsuarioFirmante findListaUsuariosFirmantes(FiltroUsuarioFirmante pFiltro) throws Exception;
	
	public UsuarioAutorizadorOrdenCompra getUsuarioFirmantePorId(long pIdUsuarioFirmante) throws TrascenderException;
}
