/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.system.interfaces;

import javax.ejb.Remote;

import com.trascender.compras.recurso.filtros.FiltroFacturaProveedor;

/**
 * Remote interface for SystemAdministracionFacturaProveedor.
 */
@Remote
public interface SystemAdministracionFacturaProveedor
{
	
	public static final String JNDI_NAME = "ejb/SystemAdministracionFacturaProveedor/remote";
   /**
    * Business method
    */
   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor addFacturaProveedor( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFacturaProveedor )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public FiltroFacturaProveedor findListaFacturaProveedor(FiltroFacturaProveedor pFiltro)
      throws java.lang.Exception;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor findFacturaProveedorByID( long pID )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.FacturaProveedor updateFacturaProveedor( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFactura )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void deleteFacturaProveedor( com.trascender.compras.recurso.persistent.suministros.FacturaProveedor pFacturaProveedor )
      throws java.lang.Exception, java.rmi.RemoteException;
   
}
