/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.system.interfaces;

import javax.ejb.Remote;

import com.trascender.compras.recurso.filtros.FiltroCondicionCompra;

@Remote
public interface SystemAdministracionCondicionCompra
{
	
	public static final String JNDI_NAME = "ejb/SystemAdministracionCondicionCompra/remote";

   public void setLlave( long pLlave )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.CondicionCompra addCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public FiltroCondicionCompra findCondicionCompra( FiltroCondicionCompra pFiltro )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public com.trascender.compras.recurso.persistent.suministros.CondicionCompra updateCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompa )
      throws java.lang.Exception, java.rmi.RemoteException;

   /**
    * Business method
    */
   public void deleteCondicionCompra( com.trascender.compras.recurso.persistent.suministros.CondicionCompra pCondicionCompra )
      throws java.lang.Exception, java.rmi.RemoteException;

}
