/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.compras.system.interfaces;

import java.util.List;

import javax.ejb.Remote;

import com.arjuna.ats.internal.jdbc.drivers.jndi;
import com.trascender.compras.recurso.filtros.FiltroLiquidacionCompra;
import com.trascender.compras.recurso.persistent.suministros.Factura;
import com.trascender.compras.recurso.persistent.suministros.LiquidacionCompra;

@Remote
public interface SystemAdministracionFactura { 
	
	public static final String JNDI_NAME = "ejb/SystemAdministracionFactura/remote";
	
	public void setLlave(long pLlave) throws java.rmi.RemoteException;
		
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws java.lang.Exception
	 * @throws java.rmi.RemoteException
	 */
	public com.trascender.compras.recurso.persistent.suministros.LineaFactura getLineaFacturaPorId(long pId) throws java.lang.Exception, java.rmi.RemoteException;
	
	/**
	 * Business method
	 * @param pId
	 * @return
	 * @throws java.lang.Exception
	 * @throws java.rmi.RemoteException
	 */
	public com.trascender.compras.recurso.persistent.suministros.Factura getFacturaPorId(long pId) throws java.lang.Exception, java.rmi.RemoteException;
	
	/**
	 * Business method
	 * @param pProveedor
	 * @param pDesde
	 * @param pHasta
	 * @param pEstado
	 * @return
	 * @throws java.lang.Exception
	 * throws java.rmi.RemoteException
	 */
	public List<Factura> findListaFactura(com.trascender.compras.recurso.persistent.suministros.Proveedor pProveedor,
			java.util.Date pDesde,java.util.Date pHasta, com.trascender.compras.recurso.persistent.suministros.Factura.Estado pEstado)	
			throws java.lang.Exception, java.rmi.RemoteException;
	
	public void addLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public LiquidacionCompra updateLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public void deleteLiquidacionCompra(LiquidacionCompra pLiquidacionCompra) throws Exception;
	public LiquidacionCompra getLiquidacionCompraPorId(Long pId) throws Exception;
	public FiltroLiquidacionCompra findListaLiquidacionCompra(FiltroLiquidacionCompra pFiltro) throws Exception;
}
