/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.business.interfaces;

import java.util.ArrayList;

import javax.ejb.Local;

import com.trascender.habilitaciones.recurso.filtros.FiltroObra;
import com.trascender.habilitaciones.recurso.persistent.Obligacion;

@Local
public interface BusinessDocumentoPlanObraLocal {
	
	public static final String JNDI_NAME = "ejb/BusinessDocumentoPlanObraLocal/local";

   public com.trascender.habilitaciones.recurso.persistent.pfo.Obra addObra( com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra ) throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.Obra updateObra( com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra ) throws java.lang.Exception;

   public void deleteObra( com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra ) throws java.lang.Exception;

   @SuppressWarnings("unchecked")
   public FiltroObra findListaObras(FiltroObra pFiltro) throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.Obra getObraPorId( long pId ) throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra addDocumentoPlanObra( com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra pDocumentoPlanObra ) throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra updateDocumentoPlanObra( com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra pDocumentoPlanObra ) throws java.lang.Exception;

   public void deleteDocumentoPlanObra( com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra pDocumentoPlanObra ) throws java.lang.Exception;

   /**
    * Recupera la lista de documentos especializados de SHPS de una persona
    * @param pPersona pPersona
    * @return listado de documentos especializados
    * @throws Exception
    */
   @SuppressWarnings("unchecked")
   public java.util.List findListaDocumentosPlanObra( com.trascender.framework.recurso.persistent.Persona pPersona,java.lang.Integer pNumeroRegistro,com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra ) throws java.lang.Exception;

   /**
    * Recupera el listado de obligaciones del documento plan de obra
    * @param pPersona
    * @param pNumeroRegistro
    * @return 
    * @throws Exception
    */
   @SuppressWarnings("unchecked")
   public java.util.List findListaObligacionPlanObra( com.trascender.framework.recurso.persistent.Persona pPersona,java.lang.Integer pNumeroRegistro,com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra )
   throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra addPlanCuentaObra( com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra pPlanCuentaObra ) 
   throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra updatePlanCuentaObra( com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra pPlanCuentaObra ) 
   throws java.lang.Exception;

   public void deletePlanCuentaObra( com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra pPlanCuentaObra ) 
   throws java.lang.Exception;

   @SuppressWarnings("unchecked")
   public java.util.List findListaPlanCuentaObra( java.lang.String pNombre ) 
   throws java.lang.Exception;

   public com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra getPlanCuentaObraPorId( long pId ) 
   throws java.lang.Exception;

   @SuppressWarnings("unchecked")
   public void anularObligacionesFromObra(ArrayList<Obligacion> pListaObligacionesFromObra, java.util.List pListaCuadra) 
   throws java.lang.Exception;
  
   /**
    * Genera las obligaciones para todas los propietarios de parcelas que se encuentren dentro de las cuadras que pertenecen a una obra
    * @param pPlantillaObligacion
    * @param pObra
    * @param pPlanCuentaDefecto
    * @throws Exception
    */
   public int generarObligacionesFromObra( com.trascender.habilitaciones.recurso.persistent.PlantillaObligacion pPlantillaObligacion,com.trascender.habilitaciones.recurso.persistent.pfo.Obra pObra,com.trascender.habilitaciones.recurso.persistent.pfo.PlanCuentaObra pPlanCuentaDefecto ) 
   throws java.lang.Exception;

   /**
    * Recupera el documento plan de obra para la obligación especificada
    * @param pObligacion
    * @return 
    * @throws Exception
    */
   public com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra getDocumentoPlanObra( com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion ) 
   throws java.lang.Exception;

   /**
    * Recupera el listado de cuadras afectadas de un documentoPFO
    * @param pDocumentoPlanObra
    * @return 
    */
   @SuppressWarnings("unchecked")
   public java.util.List getListaCuadrasAfectadasFromDocumentoPFO( com.trascender.habilitaciones.recurso.persistent.pfo.DocumentoPlanObra pDocumentoPlanObra ) 
   throws java.lang.Exception;

}
