/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.habilitaciones.recurso.filtros.FiltroPlantillaObligacion;
import com.trascender.habilitaciones.recurso.persistent.Obligacion;
import com.trascender.habilitaciones.recurso.persistent.PlantillaObligacion;
import com.trascender.habilitaciones.recurso.persistent.TipoObligacion;


/**
 * Local interface for BusinessPlantillaObligacion.
 */

@Local
public interface BusinessPlantillaObligacionLocal {
	
	public static final String JNDI_NAME = "ejb/BusinessPlantillaObligacionLocal/local";
	
   /**
    * Agrega una plantilla de obligación al sistema
    * @param pPlantillaObligacion plantilla de obligación a agregar
 * @return 
    * @throws Exception
    */
   public PlantillaObligacion addPlantillaObligacion( PlantillaObligacion pPlantillaObligacion ) throws Exception;

   /**
    * Actualiza los datos de una plantilla de obligacion
    * @param pPlnatillaObligacion plantilla de obligación con los datos actualizados
 * @return 
    * @throws Exception
    */
   public PlantillaObligacion updatePlantillaObligacion( PlantillaObligacion pPlantillaObligacion ) throws Exception;

   /**
    * Elimina físicamente una plantilla de obligacion
    * @param pPlantillaObligacion plantilla de obligación a eliminar
    * @throws Exception plantilla de obligacion a eliminar
    */
   public void deletePlantillaObligacion(PlantillaObligacion pPlantillaObligacion ) throws Exception;

   /**
    * Recupera un listado de plantillas de obligación
    * @param pNombre primeras letras del nombre de la plantilla de obligacion
    * @return Listado
    * @throws Exception
    */
   public FiltroPlantillaObligacion findListaPlantillaObligacion(FiltroPlantillaObligacion pFiltro) throws Exception;

   public List<PlantillaObligacion> findPlantillasObligacionTasaMenor();
   
   /**
    * Genera un arbol de obligaciones a partir de la plantilla de obligaciones
    * @param pPersona persona a la que pertenece la obligacion
    * @param pPlantillaObligacion plantilla de obligacion de la cual tomar como parámetro
    * @return Obligación
    * @throws Exception
    */
   public Obligacion generarArbolObligacion(PlantillaObligacion pPlantillaObligacion ) throws Exception;
   
   /**
    * Busca Plantillas de Obligacion por id
    * @param pId
    * @return
    * @throws Exception
    */
   public PlantillaObligacion getPlantillaObligacion(long pId) throws java.lang.Exception;
   public boolean esTipoObligacionTasaMenor(TipoObligacion pTipo);
   public PlantillaObligacion getPlantillaObligacionFromObligacion(Obligacion pObligacion) throws Exception;
   
}
