/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.habilitaciones.business.interfaces;

import javax.ejb.Remote;

/**
 * Remote interface for ControlHabilitaciones.
 */
@Remote
public interface ControlHabilitaciones
{
	
	public static final String JNDI_NAME = "ejb/ControlHabilitaciones/remote";

   public boolean generateGrupoRecusosHabilitaciones(  )
      throws java.lang.Exception, java.rmi.RemoteException;

}
