/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.business.interfaces;

import java.util.List;
import java.util.Set;

import javax.ejb.Local;

import com.trascender.compras.recurso.persistent.inventario.Articulo;
import com.trascender.contabilidad.recurso.filtros.FiltroCuenta;
import com.trascender.contabilidad.recurso.persistent.AsociacionRefinanciacion;
import com.trascender.contabilidad.recurso.persistent.BajaArticulo;
import com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario;
import com.trascender.contabilidad.recurso.persistent.Cuenta;
import com.trascender.contabilidad.recurso.persistent.CuentaArticulo;
import com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario;
import com.trascender.contabilidad.recurso.persistent.CuentaInteresRecargo;
import com.trascender.habilitaciones.recurso.persistent.ConceptoPorMora;
import com.trascender.habilitaciones.recurso.persistent.TipoModificador;
import com.trascender.habilitaciones.recurso.persistent.TipoTasa;
import com.trascender.saic.recurso.persistent.ParametroAsociacion;
import com.trascender.saic.recurso.persistent.refinanciacion.DocumentoRefinanciacion;

/**
 * Local interface for BusinessPlanDeCuenta.
 */
@Local
public interface BusinessPlanDeCuentaLocal
{
	
	public static final String JNDI_NAME = "BusinessPlanDeCuentaLocal";
   /**
    * Business method
    * @param pPlanDeCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.PlanDeCuenta addPlanDeCuenta( com.trascender.contabilidad.recurso.persistent.PlanDeCuenta pPlanDeCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pPlanDeCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.PlanDeCuenta updatePlanDeCuenta( com.trascender.contabilidad.recurso.persistent.PlanDeCuenta pPlanDeCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.PlanDeCuenta getPlanDeCuentaByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pPlanDeCuenta
    * @throws java.lang.Exception    */
   public void deletePlanDeCuenta( com.trascender.contabilidad.recurso.persistent.PlanDeCuenta pPlanDeCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pDescripcion
    * @param pFechaDesde
    * @param pFechaHasta
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaPlanDeCuenta( java.lang.String pDescripcion,java.util.Date pFechaDesde,java.util.Date pFechaHasta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Cuenta updateCuenta( com.trascender.contabilidad.recurso.persistent.Cuenta pCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuenta
    * @throws java.lang.Exception    */
   public void deleteCuenta( com.trascender.contabilidad.recurso.persistent.Cuenta pCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Cuenta getCuentaByID( java.lang.Long pId ) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuenta
    * @return 
    * @throws java.lang.Exception    */
   public void validarCuenta (com.trascender.contabilidad.recurso.persistent.Cuenta pCuenta) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pNombre
    * @param pAbreviatura
    * @param pCodigoImputacion
    * @param pPlanDeCuenta
    * @param pTipoCuenta
    * @return 
    * @throws java.lang.Exception    */
   public FiltroCuenta findListaCuenta(FiltroCuenta pFiltro) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoCuenta addTipoCuenta( com.trascender.contabilidad.recurso.persistent.TipoCuenta pTipoCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoCuenta updateTipoCuenta( com.trascender.contabilidad.recurso.persistent.TipoCuenta pTipoCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIdTipoCuenta
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoCuenta getTipoCuentaByID( java.lang.Long pIdTipoCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoCuenta
    * @throws java.lang.Exception    */
   public void deleteTipoCuenta( com.trascender.contabilidad.recurso.persistent.TipoCuenta pTipoCuenta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pNombre
    * @param pAbreviatura
    * @param pOperaMovimientosCaja
    * @param pOperaAsientos
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaTipoCuenta( java.lang.String pNombre,com.trascender.contabilidad.recurso.persistent.TipoCuenta.Abreviatura pAbreviatura,com.trascender.contabilidad.recurso.persistent.TipoCuenta.Opera pOperaMovimientosCaja,com.trascender.contabilidad.recurso.persistent.TipoCuenta.Opera pOperaAsientos ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoBalance
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoBalance addTipoBalance( com.trascender.contabilidad.recurso.persistent.TipoBalance pTipoBalance ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoBalance
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoBalance updateTipoBalance( com.trascender.contabilidad.recurso.persistent.TipoBalance pTipoBalance ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.TipoBalance getTipoBalanceByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoBalance
    * @throws java.lang.Exception    */
   public void deleteTipoBalance( com.trascender.contabilidad.recurso.persistent.TipoBalance pTipoBalance ) throws java.lang.Exception;

   /**
    * Business method
    * @param pNombre
    * @param pFechaDesde
    * @param pFechaHasta
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaTipoBalance( java.lang.String pNombre,java.util.Date pFechaDesde,java.util.Date pFechaHasta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Balance getBalanceByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pNombre
    * @param pFechaDesde
    * @param pFechaHasta
    * @param pTipoBalance
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaBalance( java.lang.String pNombre,java.util.Date pFechaDesde,java.util.Date pFechaHasta,com.trascender.contabilidad.recurso.persistent.TipoBalance pTipoBalance ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipoBalance
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Balance generarBalance( com.trascender.contabilidad.recurso.persistent.TipoBalance pTipoBalance ) throws java.lang.Exception;

   /**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pBalance
	 * @throws java.lang.Exception
	 */
	public void deleteBalance(com.trascender.contabilidad.recurso.persistent.Balance pBalance) throws java.lang.Exception;
			
   /**
    * Business method
    * @param pBalance
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Balance addBalance( com.trascender.contabilidad.recurso.persistent.Balance pBalance ) throws java.lang.Exception;

   /**
    * Business method
    * @param pFechaDesde
    * @param pFechaHasta
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaLibroDiario( java.util.Date pFechaDesde,java.util.Date pFechaHasta ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaModificador
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaModificador addCuentaModificador( com.trascender.contabilidad.recurso.persistent.CuentaModificador pCuentaModificador ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaModificador
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaModificador updateCuentaModificador( com.trascender.contabilidad.recurso.persistent.CuentaModificador pCuentaModificador ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaModificador
    * @throws java.lang.Exception    */
   public void deleteCuentaModificador( com.trascender.contabilidad.recurso.persistent.CuentaModificador pCuentaModificador ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaModificador getCuentaModificadorByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuenta
    * @param pTipoModificador
    * @param pPeriodo
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaCuentaModificador( Cuenta pCuenta,
		   TipoModificador pTipoModificador) throws java.lang.Exception;

   public CuentaInteresRecargo addCuentaInteresRecargo(CuentaInteresRecargo pCuentaInteresRecargo) throws java.lang.Exception;
   
   public CuentaInteresRecargo updateCuentaInteresRecargo(CuentaInteresRecargo pCuentaInteresRecargo) throws java.lang.Exception;
   
   public void deleteCuentaInteresRecargo(CuentaInteresRecargo pCuentaInteresRecargo) throws java.lang.Exception;
   
   public CuentaInteresRecargo getCuentaInteresRecargoByID(Long pId) throws java.lang.Exception;
   
   public List findListaCuentaInteresRecargo(Cuenta pCuenta, ConceptoPorMora pConceptoMora) throws java.lang.Exception;
      
   /**
    * Business method
    * @param pCuentaRefinanciacion
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion addCuentaRefinanciacion( com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion pCuentaRefinanciacion ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaRefinanciacion
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion updateCuentaRefinanciacion( com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion pCuentaRefinanciacion ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaRefinanciacion
    * @throws java.lang.Exception    */
   public void deleteCuentaRefinanciacion( com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion pCuentaRefinanciacion ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaRefinanciacion getCuentaRefinanciacionByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuenta
    * @param pRefinanciacion
    * @param pPeriodo
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaCuentaRefinanciacion( 
			DocumentoRefinanciacion pRefinanciacion, 
			Integer pAnio, 
			Cuenta pCuenta ) throws java.lang.Exception;

	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pParametroAsociacion
	 * @return ParametroAsociacion
	 * @throws java.lang.Exception
	 */
	public com.trascender.saic.recurso.persistent.ParametroAsociacion addParametroAsociacion(com.trascender.saic.recurso.persistent.ParametroAsociacion pParametroAsociacion)
			throws java.lang.Exception;

	/**
	 * Business method
	 * @ejb.interface-meporcentajethod view-type ="local"
	 * @param pParametroAsociacion
	 * @return ParametroAsociacion
	 * @throws Exception
	 */
	public com.trascender.saic.recurso.persistent.ParametroAsociacion updateParametroAsociacion(com.trascender.saic.recurso.persistent.ParametroAsociacion pParametroAsociacion)
			throws Exception;

	/**
	 * Business method
	 * @ejb.interface-method view-type ="local"
	 * @param pParametroAsociacion
	 * @return 
	 * @throws Exception
	 */
	public void deleteParametroAsociacion(com.trascender.saic.recurso.persistent.ParametroAsociacion pParametroAsociacion)
			throws Exception;
		
	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pId
	 * @return
	 * @throws java.lang.Exception
	 */
	public com.trascender.saic.recurso.persistent.ParametroAsociacion getParametroAsociacionByID(Long pId) 
			throws java.lang.Exception;

	/**
	 * Business method
	 * @ejb.interface-method view-type ="local"
	 * @param
	 * @return 
	 * @throws java.lang.Exception
	 */
	public List<ParametroAsociacion> findListaParametroAsociacion()
			throws java.lang.Exception;
   

	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pListaParametrosAsociacion, pPeriodo
	 * @return 
	 * @throws java.lang.Exception
	 */
	public AsociacionRefinanciacion addAsociacionRefinanciacion(Set<ParametroAsociacion> pListaParametrosAsociacion, 
			Integer pAnio)
		throws java.lang.Exception;

	
	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pAsociacionRefinanciacion
	 * @return
	 * @throws java.lang.Exception
	 */
	public com.trascender.contabilidad.recurso.persistent.AsociacionRefinanciacion updateAsociacionRefinanciacion(AsociacionRefinanciacion pAsociacionRefinanciacion);
	
	
	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pAsociacionRefinanciacion
	 * @return 
	 * @throws java.lang.Exception
	 */
	public void deleteAsociacionRefinanciacion(com.trascender.contabilidad.recurso.persistent.AsociacionRefinanciacion pAsociacionRefinanciacion)
		throws java.lang.Exception;
	
	
	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pId
	 * @return 
	 * @throws java.lang.Exception
	 */
	public com.trascender.contabilidad.recurso.persistent.AsociacionRefinanciacion getAsociacionRefinanciacionByID(Long pId) 
		throws java.lang.Exception;

	
	/**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pPeriodo
	 * @return 
	 * @throws java.lang.Exception
	 */
	public List<AsociacionRefinanciacion>  findListaAsociacionRefinanciacion (
			Integer pAnio) throws java.lang.Exception;
	
	
   /**
    * Business method
    * @param pCuentaConceptoIngresoVario
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario addCuentaConceptoIngresoVario(
			com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario pCuentaConceptoIngresoVario) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuentaConceptoIngresoVario
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario updateCuentaConceptoIngresoVario(
			com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario pCuentaConceptoIngresoVario) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuentaConceptoIngresoVario
    * @throws java.lang.Exception
    */
   public void deleteCuentaConceptoIngresoVario(
			com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario pCuentaConceptoIngresoVario) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pId
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaConceptoIngresoVario getCuentaConceptoIngresoVarioByID(Long pId) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pConceptoIngresoVario
    * @param pPeriodo
    * @param pCuenta
    * @return
    * @throws java.lang.Exception
    */
   public List<CuentaConceptoIngresoVario>  findListaCuentaConceptoIngresoVario(
			ConceptoIngresoVario pConceptoIngresoVario, 
			Integer pAnio, Cuenta pCuenta) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuentaTipoTasa
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa addCuentaTipoTasa( com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa pCuentaTipoTasa ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaTipoTasa
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa updateCuentaTipoTasa( com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa pCuentaTipoTasa ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaTipoTasa
    * @throws java.lang.Exception    */
   public void deleteCuentaTipoTasa( com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa pCuentaTipoTasa ) throws java.lang.Exception;

   /**
    * Business method
    * @param pId
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.CuentaTipoTasa getCuentaTipoTasaByID( java.lang.Long pId ) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuenta
    * @param pTipoTasa
    * @param pPeriodo
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaCuentaTipoTasa( Cuenta pCuenta, 
		   TipoTasa pTipoTasa,
		   Integer pAnio) throws java.lang.Exception;

   /**
    * Business method
    * @param pCuentaLineaFactura
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura addCuentaLineaFactura(com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura pCuentaLineaFactura) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuentaLineaFactura
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura updateCuentaLineaFactura(com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura pCuentaLineaFactura) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pCuentaLineaFactura
    * @return
    * @throws java.lang.Exception
    */
   public void deleteCuentaLineaFactura(com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura pCuentaLineaFactura) throws java.lang.Exception;
   
   /**
	 * Business method
	 * @ejb.interface-method view-type="local"
	 * @param pLineaFactura
	 * @return
	 * @throws Exception
	 */
	public com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura getCuentaLineaFactura(com.trascender.compras.recurso.persistent.suministros.LineaFactura pLineaFactura) throws java.lang.Exception;
	
   /**
    * Business method
    * @param pCuentaLineaFactura
    * @return
    * @throws java.lang.Exception
    */
   public com.trascender.contabilidad.recurso.persistent.CuentaLineaFactura getCuentaLineaFacturaPorId(long pId) throws java.lang.Exception;
   
   /**
    * Business method
    * @param pLineaFactura
    * @param pCuenta
    * @param pPeriodo
    * @return
    * @throws java.lang.Exception
    */
   
   public java.util.List findListaCuentaLineaFactura(
		   com.trascender.compras.recurso.persistent.suministros.LineaFactura pLineaFactura,
		   com.trascender.contabilidad.recurso.persistent.Cuenta pCuenta,
		   com.trascender.framework.recurso.transients.Periodo pPeriodo) throws java.lang.Exception;
   
   public CuentaArticulo addCuentaArticulo(CuentaArticulo pCuentaArticulo) throws java.lang.Exception;
   
   public CuentaArticulo updateCuentaArticulo(CuentaArticulo pCuentaArticulo) throws java.lang.Exception;
   
//   public CuentaArticulo deleteCuentaArticulo(CuentaArticulo pCuentaArticulo) throws java.lang.Exception;
   
   public List<CuentaArticulo> findListaCuentaArticulo(Articulo pArticulo, Integer pAnio, Cuenta pCuenta) throws java.lang.Exception;
   
   public CuentaArticulo getCuentaArticuloPorId(long pIdCuentaArticulo) throws Exception;
   
   public BajaArticulo addBajaArticulo(BajaArticulo pBajaArticulo) throws Exception;
   
   
   /**
    * Business method
    * @param pCuenta
    * @return 
    * @throws Exception    */
   public com.trascender.framework.recurso.persistent.referencia.CuentaRfr getCuentaRfr( com.trascender.contabilidad.recurso.persistent.Cuenta pCuenta ) throws java.lang.Exception;
   
   /**
	 * Business method
	 * @param pPlanDeCuenta
	 * @return
	 * @throws Exception
	 */
	public com.trascender.contabilidad.recurso.persistent.PlanDeCuenta importarPlanDeCuenta(com.trascender.contabilidad.recurso.persistent.PlanDeCuenta pPlanDeCuenta)
			throws Exception;

	

	}
