/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.contabilidad.recurso.filtros.FiltroConceptoIngresoVario;
import com.trascender.contabilidad.recurso.filtros.FiltroIngresoVario;
import com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario;
import com.trascender.framework.recurso.persistent.Usuario;

/**
 * Local interface for BusinessIngresoVario.
 */

@Local
public interface BusinessIngresoVarioLocal
{
	
	public static final String JNDI_NAME = "BusinessIngresoVarioLocal";
   /**
    * Business method
    * @param pConceptoIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario addConceptoIngresoVario( com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario pConceptoIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pConceptoIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario updateConceptoIngresoVario( com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario pConceptoIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pConceptoIngresoVario
    * @throws java.lang.Exception    */
   public void deleteConceptoIngresoVario( com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario pConceptoIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIdConceptoIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.ConceptoIngresoVario getConceptoIngresoVarioByID( java.lang.Long pIdConceptoIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.IngresoVario addIngresoVario( com.trascender.contabilidad.recurso.persistent.IngresoVario pIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.IngresoVario updateIngresoVario( com.trascender.contabilidad.recurso.persistent.IngresoVario pIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIdIngresoVario
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.IngresoVario getIngresoVarioByID( java.lang.Long pIdIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pIngresoVario
    * @throws java.lang.Exception    */
   public void deleteIngresoVario( com.trascender.contabilidad.recurso.persistent.IngresoVario pIngresoVario ) throws java.lang.Exception;

   /**
    * Business method
    * @param pFiltro
    * @return 
    * @throws java.lang.Exception    */
   public FiltroIngresoVario findListaIngresoVario(FiltroIngresoVario pFiltro) throws java.lang.Exception;

   /**
    * Business method
    * @param pFiltro
    * @return 
    * @throws java.lang.Exception    */
   public FiltroConceptoIngresoVario findListaConceptoIngresoVario(FiltroConceptoIngresoVario pFiltro) throws java.lang.Exception;

   public List<ConceptoIngresoVario> findListaConceptoIngresoVarioPorUsuario(Usuario pUsuario) throws java.lang.Exception;
}
