/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.business.interfaces;

import javax.ejb.Local;

/**
 * Local interface for BusinessImpresionTicketCaja.
 */
@Local
public interface BusinessImpresionTicketCajaLocal
{
	
	public static final String JNDI_NAME = "BusinessImpresionTicketCajaLocal";
   /**
    * Business method
    * @param pIdTicketCaja
    * @throws Exception    */
   public void getReporteTicketCaja( java.lang.Long pIdTicketCaja ) throws java.lang.Exception;

}
