/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.business.interfaces;

import java.util.Set;

import javax.ejb.Local;

/**
 * Local interface for BusinessPresupuesto.
 */

@Local
public interface BusinessPresupuestoLocal
{
	
	public static final String JNDI_NAME = "BusinessPresupuestoLocal";
   /**
    * Business method
    * @param pPresupuesto
    * @return 
    * @throws java.lang.Exception 
       */
   public com.trascender.contabilidad.recurso.persistent.Presupuesto addPresupuesto( com.trascender.contabilidad.recurso.persistent.Presupuesto pPresupuesto ) throws java.lang.Exception;

   /**
    * Business method
    * @param pPresupuesto
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Presupuesto updatePresupuesto( com.trascender.contabilidad.recurso.persistent.Presupuesto pPresupuesto, 
		   com.trascender.framework.recurso.persistent.Usuario pUsuario) throws java.lang.Exception;

   /**
    * Business method
    * @param pPresupuesto
    * @throws java.lang.Exception    */
   public void deletePresupuesto( com.trascender.contabilidad.recurso.persistent.Presupuesto pPresupuesto ) throws java.lang.Exception;

   
   /**
    * Business method
    * @param pListaLineaPresupuesto
    * @throws java.lang.Exception
    */
   public void deleteListaLineaPresupuesto(Set<com.trascender.contabilidad.recurso.persistent.LineaPresupuesto> pListaLineaPresupuesto, com.trascender.framework.recurso.persistent.Usuario pUsuario) throws java.lang.Exception;
   
   
   /**
    * 
    * Business method
    * @param pIdPresupuesto
    * @return 
    * @throws java.lang.Exception    */
   public com.trascender.contabilidad.recurso.persistent.Presupuesto getPresupuestoByID( java.lang.Long pIdPresupuesto ) throws java.lang.Exception;

   /**
    * Business method
    * @param pTipo
    * @param pEstado
    * @param pFechaDesde
    * @param pFechaHasta
    * @return 
    * @throws java.lang.Exception    */
   public java.util.List findListaPresupuesto( com.trascender.contabilidad.recurso.persistent.Presupuesto.Tipo pTipo,com.trascender.contabilidad.recurso.persistent.Presupuesto.Estado pEstado,java.util.Date pFechaDesde,java.util.Date pFechaHasta ) throws java.lang.Exception;

}
