/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.contabilidad.business.interfaces;

import javax.ejb.Local;

/**
 * Remote interface for ControlCaja.
 */
@Local
public interface ControlCaja
{
	
	public static final String JNDI_NAME = "ControlCaja";
   /**
    * Business method
    * @return 
    * @throws Exception    */
   public boolean generateGrupoRecursosCaja(  )
      throws java.lang.Exception, java.rmi.RemoteException;

}
