/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.saic.business.interfaces;

import java.util.List;
import java.util.Set;

import javax.ejb.Local;

import com.trascender.catastro.recurso.persistent.Parcela;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.transients.Periodo;
import com.trascender.habilitaciones.recurso.persistent.Obligacion;
import com.trascender.habilitaciones.recurso.persistent.TipoObligacion;
import com.trascender.saic.recurso.filtros.FiltroLiquidacionTasaRefer;
import com.trascender.saic.recurso.persistent.EstadoCuentaTemporalOSP;
import com.trascender.saic.recurso.persistent.EstadoCuentaTemporalPFO;
import com.trascender.saic.recurso.persistent.EstadoCuentaTemporalSHPS;
import com.trascender.saic.recurso.persistent.EstadoCuentaTemporalTGI;
import com.trascender.saic.recurso.persistent.LiquidacionTasa;
import com.trascender.saic.recurso.persistent.RegistroDeuda.EstadoRegistroDeuda;
import com.trascender.saic.recurso.references.LiquidacionTasaRefer;
import com.trascender.saic.recurso.transients.EstadoCuentaContribuyente;
import com.trascender.saic.recurso.transients.LiquidacionTasaAgrupada;

/**
 * Local interface for BusinessEstadoCuentaContribuyente.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Local
public interface BusinessEstadoCuentaContribuyenteLocal{
	   public static final String JNDI_NAME="BusinessEstadoCuentaContribuyenteLocal/local";
   /**
    * Recupera el listado de obligaciones de un contribuyente
    * @param pIdTramite nro del tramite
    * @param pPersona contribuyente asociado
    * @param pEstadoObligacion
    * @return 
    * @throws Exception
    */
   public java.util.List getListaObligacionesContribuyente(Long pIdTramite, com.trascender.framework.recurso.persistent.Persona pPersona,com.trascender.habilitaciones.recurso.persistent.Obligacion.Estado pEstadoObligacion ) throws java.lang.Exception;
   
   /**
    * Recupera el listado de DocHabEspecializados de un contribuyente
    * @param pPersona contribuyente
    * @return 
    * @throws Exception
    */
   public java.util.List getListaDocEspecializadosContribuyente(Persona pPersona) throws Exception;
   
   /**
    * Recupera el listado de LiquidacionTasa de una obligacion
    * @param pObligacion
    * @return 
    * @throws Exception
    */
   public java.util.List getListaDeudasContribuyente(Obligacion pObligacion ) throws java.lang.Exception;
   
   /**
    * Recupera el listado de RegistrosDeuda de una obligacion
    * @param pObligacion
    * @param pEstadoRegistroDeuda
    * @return 
    * @throws Exception
    */
   public java.util.List getListaRegistrosDeudaObligacion( com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion, EstadoRegistroDeuda pEstadoRegistroDeuda, String pEstado, Periodo pPeriodo) throws java.lang.Exception;

   public java.util.List getListaDeudasContribuyente( java.util.List pListaObligaciones ) throws java.lang.Exception;
   
   /**
    * Recupera el listado de obligaciones de un contribuyente
    * @param pPersona contribuyente asociado
    * @param pEstadoObligacion
    * @return 
    * @throws Exception
    */
   public java.util.List getListaObligacionesContribuyente(com.trascender.framework.recurso.persistent.Persona pPersona,com.trascender.habilitaciones.recurso.persistent.Obligacion.Estado pEstadoObligacion ) throws java.lang.Exception;
   
   /**
    * Recupera el listado de estados de cuentas de los contribuyentes de la tasa TGI 
    * @return
    * @throws Exception
    */
   public java.util.List<EstadoCuentaTemporalTGI> getListaEstadoCuentasTemporalTGI() throws Exception;

   /**
    * Recupera el listado de estados de cuentas de los contribuyentes de la tasa SHPS 
    * @return
    * @throws Exception
    */
   public java.util.List<EstadoCuentaTemporalSHPS> getListaEstadoCuentasTemporalSHPS() throws Exception;
   
   /**
    * Recupera el listado de estados de cuentas de los contribuyentes de la tasa PFO 
    * @return
    * @throws Exception
    */
   public java.util.List<EstadoCuentaTemporalPFO> getListaEstadoCuentasTemporalPFO() throws Exception;
   
   /**
    * Recupera el listado de estados de cuentas de los contribuyentes de la tasa OSP 
    * @return
    * @throws Exception
    */
   public java.util.List<EstadoCuentaTemporalOSP> getListaEstadoCuentasTemporalOSP() throws Exception;
   
   /**
    * Recupera el listado de estados de cuentas del contribuyente 
    * @return
    * @throws Exception
    */
   public java.util.List<EstadoCuentaContribuyente> getListaEstadosCuentaContribuyente(Persona pPersona, Obligacion.Estado pEstadoObligacion) throws Exception;
   
 
		/**
		 * 
		 * @param pPersona
		 * @param pTiposObligacion
		 * @return
		 * @throws Exception
		 */
	public Set<Obligacion> getListaObligacionesContribuyentePorTasa(Persona pPersona, TipoObligacion... pTiposObligacion) throws Exception;
	
	public Set getListaDeudasContribuyente(Obligacion pObligacion, Periodo pPeriodo) throws Exception;
	
	public LiquidacionTasaAgrupada inicializarLiquidacionTasaAgrupada(LiquidacionTasaRefer pLiquidacion, boolean actualizar);
	
	public FiltroLiquidacionTasaRefer findListaLiquidacionTasaRefer(FiltroLiquidacionTasaRefer pFiltro) throws Exception;

	void setLlave(long llave);
}
