/*
 * Generated by XDoclet - Do not edit!
 */
package com.trascender.saic.business.interfaces;

import java.util.List;

import javax.ejb.Local;

import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.saic.recurso.persistent.auditoriaTributaria.AuditoriaTributaria;
import com.trascender.saic.recurso.persistent.refinanciacion.DocumentoRefinanciacion;

/**
 * Local interface for BusinessRefinanciacion.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Local
public interface BusinessRefinanciacionLocal
{
	public static final String JNDI_NAME="BusinessRefinanciacionLocal/local";
	
   public java.util.Set calcularCuotasRefinanciacion( com.trascender.saic.recurso.persistent.refinanciacion.DocumentoRefinanciacion pDocumentoRefinanciacion ) throws Exception;

   public void addRefinanciacion( com.trascender.saic.recurso.persistent.refinanciacion.DocumentoRefinanciacion pDocumentoRefinanciacion, AuditoriaTributaria pAuditoria ) throws java.lang.Exception;

   public void updateRefinanciacion( com.trascender.saic.recurso.persistent.refinanciacion.DocumentoRefinanciacion pDocumentoRefinanciacion ) throws java.lang.Exception;
   
   public DocumentoRefinanciacion getDocumentoRefinanciacion(long pIdDocGeneradorDeuda) throws Exception;
		   
   public List<DocumentoRefinanciacion> findListaRefinanciaciones(Persona pPersona, Integer pNumeroRefinanciacion) throws Exception;
}
