/*
 * Generated by XDoclet - Do not edit!
 */

package com.trascender.saic.business.interfaces;

import java.util.ArrayList;
import java.util.List;

import javax.ejb.Local;

import com.trascender.catastro.recurso.persistent.Calle;
import com.trascender.framework.exception.TrascenderException;
import com.trascender.framework.recurso.persistent.Persona;
import com.trascender.framework.recurso.transients.Calendario;
import com.trascender.habilitaciones.recurso.persistent.CuotaLiquidacion;
import com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS;
import com.trascender.habilitaciones.recurso.persistent.PeriodoLiquidacion;
import com.trascender.habilitaciones.recurso.persistent.tasaMenor.PlantillaDocumentoTasaMenor;
import com.trascender.habilitaciones.recurso.persistent.tasaMenor.RegistroValuadoTasaMenor;
import com.trascender.saic.recurso.filtros.FiltroDDJJSHPS;
import com.trascender.saic.recurso.filtros.FiltroValorMedidor;

/**
 * Local interface for BusinessRegistroValuado.
 * 
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
@Local
public interface BusinessRegistroValuadoLocal {
	public static final String JNDI_NAME = "BusinessRegistroValuadoLocal/local";

	/**
	 * Recupera el siguiente período según los 3 parámetros
	 * 
	 * @param pPeriodicidad
	 *            periodicidad a la que corresponde el período
	 * @param pNumeroPeriodo
	 *            número de período actual
	 * @param pAño
	 *            año al que corresponde el período
	 * @return
	 * @ejb.interface-method view-type = "local"
	 */

	public DeclaracionJuradaSHPS getNuevaDDJJSHPS(Persona pPersona, CuotaLiquidacion pPeriodo, String pNroInscripcion, ArrayList pListaAtributosDinamicos) throws java.lang.Exception;

	public FiltroDDJJSHPS getListaDDJJSHPS(FiltroDDJJSHPS pFiltro) throws Exception;

	public DeclaracionJuradaSHPS getDDJJSHPSporId(long pIdDeclaracion) throws Exception;

	/**
	 * Agrega un registro Valuado
	 * 
	 * @param pRegistroValuado
	 *            registro valuado a agregar
	 * @throws Exception
	 */
	public void addRegistroValuado(com.trascender.habilitaciones.recurso.persistent.RegistroValuado pRegistroValuado) throws java.lang.Exception;

	/**
	 * actualiza los datos de un registro valuado
	 * 
	 * @param pRegistroValuado
	 *            registro valuado a actualizar
	 * @throws Exception
	 */
	public void updateRegistroValuado(com.trascender.habilitaciones.recurso.persistent.RegistroValuado pRegistroValuado) throws java.lang.Exception;

	/**
	 * Elimina un registro valuado
	 * 
	 * @param pRegistroValuado
	 *            registro valuado a eliminar
	 * @throws Exception
	 */
	public void deleteRegistroValuado(com.trascender.habilitaciones.recurso.persistent.RegistroValuado pRegistroValuado) throws java.lang.Exception;

	/**
	 * Recupera un listado de registros valuados
	 * 
	 * @return Listado de registros valuados
	 * @throws Exception
	 */
	public java.util.List findListaRegistrosValuados() throws java.lang.Exception;

	public void addDDJJSHPS(DeclaracionJuradaSHPS pDDJJSHPS) throws java.lang.Exception;
	
	public DeclaracionJuradaSHPS addDDJJSHPSParaLiquidar(DeclaracionJuradaSHPS pDDJJSHPS) throws java.lang.Exception;

	public void updateDDJJSHPS(com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS pDeclaracionJuradaSHPS) throws java.lang.Exception;

	public void deleteDDJJSHPS(com.trascender.habilitaciones.recurso.persistent.DeclaracionJuradaSHPS pDeclaracionJuradaSHPS) throws java.lang.Exception;

	public java.util.List getListaNuevasMedidasServiciosOSP(Calle pCalle, CuotaLiquidacion pCuota, com.trascender.habilitaciones.recurso.persistent.osp.ServicioOSP pServicio,
			String pCodigoMedidor) throws java.lang.Exception;

	public void addListaValorMedidor(java.util.List pValoresMedidores) throws java.lang.Exception;

	public void updateValorMedidor(com.trascender.habilitaciones.recurso.persistent.ValorMedidor pValorMedidor) throws java.lang.Exception;

	public FiltroValorMedidor findListaValoresMedidor(FiltroValorMedidor pFiltro) throws Exception;

	public List<RegistroValuadoTasaMenor> findListaRegistrosValuadosTasaMenor(Persona pPersona, CuotaLiquidacion pCuota, PeriodoLiquidacion pPeriodo, Calendario pCalendario,
			PlantillaDocumentoTasaMenor pPlantilla);

	public List<RegistroValuadoTasaMenor> generarRegistrosTasaMenor(Persona pPersona, CuotaLiquidacion pCuota, PlantillaDocumentoTasaMenor pPlantilla) throws TrascenderException;

	public void addRegistrosValuadosTasaMenor(List<RegistroValuadoTasaMenor> pListaRegistrosValuados) throws TrascenderException;

	public void updateRegistroValuadoTasaMenor(RegistroValuadoTasaMenor pRegistroValuado) throws TrascenderException;

	public void deleteRegistroValuadoTasaMenor(RegistroValuadoTasaMenor pRegistroValuadoTasaMenor) throws Exception;

	public RegistroValuadoTasaMenor getRegistroValuadoTasaMenorPorId(long pId);

	public com.trascender.habilitaciones.recurso.persistent.ValorMedidor getValorMedidorPorId(long pIdRegistroValuado) throws java.lang.Exception;

	/**
	 * Recupera el listado de pagos de sellados de una obligacion
	 * 
	 * @param pPersona
	 * @return
	 * @throws Exception
	 */
	public java.util.List findListaPagoSellado(com.trascender.framework.recurso.persistent.Persona pPersona, com.trascender.habilitaciones.recurso.persistent.Obligacion pObligacion,
			java.lang.Boolean pPagado) throws java.lang.Exception;

}
